### ISSUE TITLE
[Insight] Text files should end with a valid new line character. - in config/routes/framework.yaml, line 5

### ISSUE THREAD

**Issue by AxelBuob** [AxelBuob/snowtricks#45]
**[in config/routes/framework.yaml, line 5](https://github.com/AxelBuob/snowtricks/blob/185aff25544a21735534a64f870f19119944d9f8/config/routes/framework.yaml#L5)**

> This file ends with no newline character, or with a different newline character than other files in your project. It won't render properly on a terminal, and it's considered a bad practice.

```
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
        
```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/06cee59b-6e5a-4266-a8e2-be595cb0258f/analyses/41?status=commit)_
